#!/bin/bash -e

USAGE="$0 <SPLIT_PATH> <SOLVE_PATH> <MERGE_PATH> <CNF_PATH> <NUM_DIVIDES> <TIMEOUT> <TIMEOUT_FACTOR> <MARCH_PATH> <LINGELING_PATH> <CREATE_THUNK>"

SPLIT_PATH=${1?$USAGE}
SOLVE_PATH=${2?$USAGE}
MERGE_PATH=${3?$USAGE}
CNF_PATH=${4?$USAGE}
NUM_DIVIDES=${5?$USAGE}
TIMEOUT=${6?$USAGE}
TIMEOUT_FACTOR=${7?$USAGE}
MARCH_PATH=${8?$USAGE}
LINGELING_PATH=${9?$USAGE}
CREATE_THUNK_PATH=${10?$USAGE}
SELF_PATH=$(readlink -f $0)


SPLIT_HASH=$(gg-hash $SPLIT_PATH)
SOLVE_HASH=$(gg-hash $SOLVE_PATH)
MERGE_HASH=$(gg-hash $MERGE_PATH)
CNF_HASH=$(gg-hash $CNF_PATH)
MARCH_HASH=$(gg-hash $MARCH_PATH)
LINGELING_HASH=$(gg-hash $LINGELING_PATH)
GG_CREATE_THUNK_HASH=$(gg-hash $(which gg-create-thunk))
GG_INIT_HASH=$(gg-hash $(which gg-init))
GG_HASH_HASH=$(gg-hash $(which gg-hash))
SELF_HASH=$(gg-hash $SELF_PATH)

rm -rf .gg

gg-init

gg-collect \
    $SPLIT_PATH \
    $SOLVE_PATH \
    $MERGE_PATH \
    $CNF_PATH \
    $MARCH_PATH \
    $LINGELING_PATH \
    $(which gg-create-thunk) \
    $(which gg-init) \
    $(which gg-hash) \
    > /dev/null

$CREATE_THUNK_PATH $SPLIT_HASH $SOLVE_HASH $MERGE_HASH $CNF_HASH $NUM_DIVIDES $TIMEOUT $TIMEOUT_FACTOR $MARCH_HASH $LINGELING_HASH $GG_INIT_HASH $GG_HASH_HASH $GG_CREATE_THUNK_HASH
